//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkflowState
    {
        public WorkflowState()
        {
            this.DocumentTasks = new HashSet<DocumentTask>();
            this.StateTransitions = new HashSet<StateTransition>();
            this.StateTransitions1 = new HashSet<StateTransition>();
            this.Workflows = new HashSet<Workflow>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DocumentTask> DocumentTasks { get; set; }
        public virtual ICollection<StateTransition> StateTransitions { get; set; }
        public virtual ICollection<StateTransition> StateTransitions1 { get; set; }
        public virtual ICollection<Workflow> Workflows { get; set; }
    }
}
