//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyCoop.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Workflow
    {
        public Workflow()
        {
            this.DocumentTasks = new HashSet<DocumentTask>();
        }
    
        public int Id { get; set; }
        public int StartStateId { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<DocumentTask> DocumentTasks { get; set; }
        public virtual WorkflowState WorkflowState { get; set; }
    }
}
